
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vending_machine_development

  username: postgres

  password: 123456789

  host: localhost

  port: 5432

test:
  <<: *default
  database: vending_machine_test

  username: postgres

  password: 123456789

  host: localhost

  port: 5432


production:
  <<: *default
  database: vending_machine_production
  username: vending_machine
  password: <%= ENV["VENDING_MACHINE_DATABASE_PASSWORD"] %>
