
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vending_machine_development

  username: <%= Rails.application.credentials.development[:username] %>

  password: <%= Rails.application.credentials.development[:password] %>

  host: <%= Rails.application.credentials.development[:host] %>

  port: <%= Rails.application.credentials.development[:port] %>

test:
  <<: *default
  database: vending_machine_test

  username: <%= Rails.application.credentials.development[:username] %>

  password: <%= Rails.application.credentials.development[:password] %>

  host: <%= Rails.application.credentials.development[:host] %>

  port: <%= Rails.application.credentials.development[:port] %>


production:
  <<: *default
  database: vending_machine_production
  username: vending_machine
  password: <%= ENV["VENDING_MACHINE_DATABASE_PASSWORD"] %>
